import { InputPlugin } from '@mark-magic/core'
import { MetaData } from '@mark-magic/epub'
import yaml from 'yaml'

export interface InputConfig {
  url: string
}

export interface NovelMeta {
  id: string
  name: string
  creator: {
    name: string
    url: string
  }
  language?: string
}

export interface NovelInputPlugin extends InputPlugin {
  /** 是否匹配 url */
  match(): boolean
  /** 获取小说元数据 */
  getMeta(): Promise<NovelMeta>
}

export function renderReadme(readme: {
  id: string
  name: string
  content: string
  creator: {
    name: string
    url: string
  }
  language?: string
  url: string
}) {
  return `
---
${yaml.stringify({
  book: {
    id: readme.id,
    title: readme.name,
    creator: readme.creator.name,
    publisher: 'Mark Magic',
    language: readme.language,
  } as MetaData,
})}
---
# ${readme.name}

${readme.content}

Author: [${readme.creator.name}](${readme.creator.url})
Source: <${readme.url}>
Generated by [Mark-Magic](https://mark-magic.rxliuli.com/en/)
  `.trim()
}
