import { InputPlugin } from '@mark-magic/core'

export interface InputConfig {
  url: string
}

export interface NovelMeta {
  id: string
  name: string
  creator: {
    name: string
    url: string
  }
}

export interface NovelInputPlugin extends InputPlugin {
  /** 是否匹配 url */
  match(): boolean
  /** 获取小说元数据 */
  getMeta?(): Promise<NovelMeta>
}

export function renderReadme(readme: {
  name: string
  content: string
  creator: {
    name: string
    url: string
  }
  url: string
}) {
  return [
    '# ' + readme.name,
    readme.content,
    `Author: [${readme.creator.name}](${readme.creator.url})`,
    `Source: <${readme.url}>`,
    `Generated by [Mark-Magic](https://mark-magic.rxliuli.com/en/)`,
  ].join('\n\n')
}
