tasks:
  - name: translate
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: './docs'
        ignore:
          - './docs/en/**'
          - './docs/.vitepress/**'
    transforms:
      - name: '@mark-magic/plugin-doctran'
        config:
          engine: 'openai'
          to: 'en'
          baseUrl: 'http://127.0.0.1:8080/v1/'
          apiKey: ${OPENAI_API_KEY}
          model: 'gpt-4'
    output:
      name: '@mark-magic/plugin-local'
      config:
        path: './docs/en'
