/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PluginConfig = BasePluginConfig | LocalPluginConfig | EpubPluginConfig

export interface ConfigSchema {
  generate: GenerateConfig[]
  [k: string]: unknown
}
export interface GenerateConfig {
  /**
   * 生成任务的名字
   */
  name: string
  input: PluginConfig
  output: PluginConfig
  [k: string]: unknown
}
/**
 * 插件配置
 */
export interface BasePluginConfig {
  /**
   * 插件名字
   */
  name: string
  /**
   * 插件配置
   */
  config?: {
    [k: string]: unknown
  }
  [k: string]: unknown
}
/**
 * 从本地目录读取或输出到本地目录
 */
export interface LocalPluginConfig {
  /**
   * 插件名字
   */
  name: '@mark-magic/plugin-local'
  /**
   * 插件配置
   */
  config: {
    /**
     * 本地目录的路径
     */
    path: string
    [k: string]: unknown
  }
  [k: string]: unknown
}
/**
 * 输出为 epub
 */
export interface EpubPluginConfig {
  /**
   * 插件名字
   */
  name: '@mark-magic/plugin-epub'
  /**
   * 插件配置
   */
  config: {
    /**
     * 输出文件的路径
     */
    path: string
    [k: string]: unknown
  }
  [k: string]: unknown
}
