/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InputPluginConfig = LocalPluginConfig
export type OutputPluginConfig = LocalPluginConfig | EpubPluginConfig | DocsPluginConfig

export interface ConfigSchema {
  generate: GenerateConfig[]
}
export interface GenerateConfig {
  /**
   * 生成任务的名字
   */
  name: string
  input: InputPluginConfig
  output: OutputPluginConfig
}
/**
 * 从本地目录读取或输出到本地目录
 */
export interface LocalPluginConfig {
  /**
   * 插件名字
   */
  name: '@mark-magic/plugin-local'
  /**
   * 插件配置
   */
  config: {
    /**
     * 本地目录的路径
     */
    path: string
  }
}
/**
 * 输出为 epub
 */
export interface EpubPluginConfig {
  /**
   * 插件名字
   */
  name: '@mark-magic/plugin-epub'
  /**
   * 插件配置
   */
  config: {
    /**
     * 输出文件的路径
     */
    path: string
    metadata?: {
      /**
       * 书籍唯一标识
       */
      id: string
      /**
       * 书籍标题
       */
      title: string
      /**
       * 作者
       */
      creator: string
      /**
       * 发布者
       */
      publisher: string
      /**
       * 语言
       */
      language: string
      /**
       * 封面图片
       */
      cover?: string
    }
  }
}
/**
 * 输出为文档网站
 */
export interface DocsPluginConfig {
  /**
   * 插件名称
   */
  name: '@mark-magic/plugin-docs'
  config: {
    /**
     * 输出文件的路径
     */
    path: string
    /**
     * 静态资源目录
     */
    public?: string
    name: string
    repo: string
    theme: {
      dark?: boolean
    }
    giscus?: {
      repo: string
      repoId: string
      category: string
      categoryId: string
      mapping: string
      'reactions-enabled': string
      'emit-metadata': string
      'input-position': string
      theme: string
      lang: string
      crossorigin: string
    }
  }
}
